build:
	go build -o ../../bin/web_crawler main.go 
run:
	go run main.go en 1 https://en.wikipedia.org/wiki/Bobby_Fischer /home/mgk/repo/go/src/github.com/tarantella-crawler/data/formatted_web_content/ 
clean:
	go clean
	
